### ISSUE TITLE
EpiPrepare steps checklist

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/EpiProcess#1]
## QC 
- [x] `fastqc`

## Trimming
- [x] `trimgalore`

## Alignment
- [x] `bowtie2` 

### Remove duplicates 
- [x] `picard SortSam` (sort by coordinates)
- [ ] `picard MarkDuplicates` (mark duplicates)
- [ ] `picard MarkDuplicates` (remove duplicates)

## Convert files 
- [ ] `samtools sort` (sort by read names)
- [ ] `samtools view` (filter and keep the mapped read pairs, convert to bam)
- [ ] `bedtools bamtobed` (convert to bed)
- [ ] `cut` (only extract the fragment related columns)

## Downsampling
- [ ] `samtools view`

## Make (normalized) bedgraph
- [ ] `samtools view`
- [ ] `bedtools genomecov`

## Peak calling 
- [ ] `seacr`
- [ ] `macs2`
- [ ] `GoPeaks`

### Prepare BigWig file 
- [ ] `samtools sort`
- [ ] `samtools index`
- [ ] `bamCoverage`

### Heatmap over transcription units
- [ ] `computeMatrix `
- [ ] `plotHeatmap`

### Heatmap over peaks  
- [ ] `computeMatrix`
- [ ] `plotHeatmap`

## Find motifs
- [ ] `findMotifsGenome.pl` 

## Genome-wide correlation
- [ ] `bedtools multicov`
